### PR TITLE
lwan return type fix for C++/C compatability

### PR DESCRIPTION
**Pull request by GuacheSuede**

### CODE REVIEW

**Comment by lpereira** [comment]
Thanks for the contribution, but I'm closing this issue as it's a duplicate of #186.

**Comment by GuacheSuede** [comment]
#186 does not work when compiled, does it work for you ?

**Comment by lpereira** [comment]
Changing the return type is not the ideal choice: an int doesn't have an attached meaning, and if an enum can be used instead, it's better. In fact, a better fix would be converting from the request flags to another enum that contains only the request methods (although that requires changing things in yet another place when a new request method is added).

And, no, #186 doesn't work with a C compiler, but I've asked the author to use a different kind of cast that will work with both C++ and C.

**Comment by GuacheSuede** [comment]
C type casting does not work in C++ in that instance.

Regarding your suggesting fix, what kind of implementation other than enum do you suggest, member functions ?

**Comment by lpereira** [comment]
Lwan is written in C, so it doesn't have member functions. If C type casting won't work in C++ in that case, maybe the best way to do it is to move the implementation to lwan-request.c and have only the prototype in the .h file.

**Comment by GuacheSuede** [comment]
Thanks @lpereira , Compilation works now.

**Pull request closed without merging**
