### PR TITLE
Install liblwan-common.a and header files.

### PR DESCRIPTION
**Pull request by byzhang**

### CODE REVIEW

**Comment by lpereira** [comment]
Nice!

I'd just add a [`.pc` file](https://wiki.freedesktop.org/www/Software/pkg-config/) in order to ensure the program that uses the library also uses the same linking options that would be used if built alongside the Lwan build system (setting `Libs.private` and whatnot).

**Comment by byzhang** [comment]
Didn't use pkg-config much before. Maybe you can merge this pull request and have a follow up commit? Or you may just make a new commit from scratch. Anyway, lwan is handy for an embedding http server :)

**Comment by lpereira** [comment]
I'll merge this commit and make the pkg-config stuff.

**Comment by lpereira** [comment]
Merged, thanks!

**Pull request merged**
