### PR TITLE
Check if -flto gcc flag is supported

### PR DESCRIPTION
**Pull request by ValtsS**
Older gcc versions do not support LTO

### CODE REVIEW

**Comment by lpereira** [comment]
I've just merged a pull request that conflicts with this change. Could you please update your patch so I can merge it?

**Comment by ValtsS** [comment]
I think that should fix the issue. I have very little experience with git & github.

**Comment by lpereira** [comment]
Make sure you have a remote to this repository: `git remote add lpereira git@github.com:lpereira/lwan.git` (you only need to do this once).

Fetch this repository: `git fetch lpereira`.

Make sure you're on the correct branch (either `master` if you're not using branches, or something else if you are) with `git branch`.

Since this patch is small, it's maybe a better idea to reset your branch to `lpereira/master` branch and rewrite the changes: `git reset --hard lpereira/master`. An alternative is to rebase your changes on top of this repository's: `git rebase lpereira/master`, but you might need to fix conflicts. Then push the changes to your repository; this PR should be updated automatically.

Yeah, Git is a bit clumsy in the beginning but you'll **g**et used to **it**.

Also, you might want to read [this document](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/) so that your name and email address are set up properly.

**Comment by lpereira** [comment]
Patch looks good; can you please just add your contact email address in Git and repush it to properly give you credits?

**Comment by ValtsS** [comment]
Should be fixed.

**Comment by lpereira** [comment]
Merged, thank you!

**Pull request closed without merging**
